#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopMnagementSystem.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ShopManage")]
	public partial class DataClasses16DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttblcompanyacdetail(tblcompanyacdetail instance);
    partial void Updatetblcompanyacdetail(tblcompanyacdetail instance);
    partial void Deletetblcompanyacdetail(tblcompanyacdetail instance);
    #endregion
		
		public DataClasses16DataContext() : 
				base(global::ShopMnagementSystem.Properties.Settings.Default.ShopManageConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses16DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses16DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses16DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses16DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblcompanyacdetail> tblcompanyacdetails
		{
			get
			{
				return this.GetTable<tblcompanyacdetail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblcompanyacdetail")]
	public partial class tblcompanyacdetail : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Company_Name;
		
		private string _Order_Booker_Name;
		
		private string _OB_Contact;
		
		private string _SO_Phone_No;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnCompany_NameChanging(string value);
    partial void OnCompany_NameChanged();
    partial void OnOrder_Booker_NameChanging(string value);
    partial void OnOrder_Booker_NameChanged();
    partial void OnOB_ContactChanging(string value);
    partial void OnOB_ContactChanged();
    partial void OnSO_Phone_NoChanging(string value);
    partial void OnSO_Phone_NoChanged();
    #endregion
		
		public tblcompanyacdetail()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Company Name]", Storage="_Company_Name", DbType="NVarChar(300)")]
		public string Company_Name
		{
			get
			{
				return this._Company_Name;
			}
			set
			{
				if ((this._Company_Name != value))
				{
					this.OnCompany_NameChanging(value);
					this.SendPropertyChanging();
					this._Company_Name = value;
					this.SendPropertyChanged("Company_Name");
					this.OnCompany_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Order Booker Name]", Storage="_Order_Booker_Name", DbType="NVarChar(50)")]
		public string Order_Booker_Name
		{
			get
			{
				return this._Order_Booker_Name;
			}
			set
			{
				if ((this._Order_Booker_Name != value))
				{
					this.OnOrder_Booker_NameChanging(value);
					this.SendPropertyChanging();
					this._Order_Booker_Name = value;
					this.SendPropertyChanged("Order_Booker_Name");
					this.OnOrder_Booker_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[OB Contact]", Storage="_OB_Contact", DbType="NVarChar(50)")]
		public string OB_Contact
		{
			get
			{
				return this._OB_Contact;
			}
			set
			{
				if ((this._OB_Contact != value))
				{
					this.OnOB_ContactChanging(value);
					this.SendPropertyChanging();
					this._OB_Contact = value;
					this.SendPropertyChanged("OB_Contact");
					this.OnOB_ContactChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[SO Phone No]", Storage="_SO_Phone_No", DbType="NVarChar(50)")]
		public string SO_Phone_No
		{
			get
			{
				return this._SO_Phone_No;
			}
			set
			{
				if ((this._SO_Phone_No != value))
				{
					this.OnSO_Phone_NoChanging(value);
					this.SendPropertyChanging();
					this._SO_Phone_No = value;
					this.SendPropertyChanged("SO_Phone_No");
					this.OnSO_Phone_NoChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
